FROM registry.gitlab.com/dwp/secure-development/registry-mirrors/chainguard/jre:openjdk-21.0.11
COPY --chown=nonroot:nonroot target/ms-document-submission-manager-*.jar /app.jar

EXPOSE 8080

USER java
ENTRYPOINT ["java", "-jar", "/app.jar"]
