workflow:
  rules:
    ####################################################################################
    ### SEC-DEV Pipeline Execution Policy                                            ###
    ####################################################################################
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    ####################################################################################
    ### MERGE REQUEST FOR RELEASE BRANCH TO MAIN OR DEVELOP NEVER RUNS PIPELINE      ###
    ####################################################################################
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^[Rr]-.*$/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(main|develop)$/'
      when: never
    ####################################################################################
    ### FEATURE BRANCHES                                                             ###
    ####################################################################################
    - if: '$CI_COMMIT_REF_NAME =~ /^[Ff]-.*$/ && $CI_PIPELINE_SOURCE != "schedule"'
      changes:
        compare_to: refs/heads/develop
        paths: ['**/*']
      when: always
    ####################################################################################
    ### DEFAULT BRANCH                                                               ###
    ####################################################################################
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "web"'
      variables:
        DOCUMENTATION: "true"
      when: always
    ####################################################################################
    ### RELEASE BRANCHES                                                             ###
    ####################################################################################
    - if: '$CI_COMMIT_REF_NAME =~ /^[Rr]-.*$/ && $CI_PIPELINE_SOURCE =~ /^(api|web)$/ && $CR_NO != null'
      variables:
        VERSION: "true"
        PROD_RELEASE: "true"
        #OIDC Config
        ASSUME_ROLE_NAME: "$PRODUCT-build-prod"
      when: always
    ####################################################################################
    ### RELEASE BRANCHES - RELEASE TESTING                                           ###
    ####################################################################################
    - if: '$CI_COMMIT_REF_NAME =~ /^[Rr]-.*$/'
      variables:
        VERSION: "true"
      when: always
    ####################################################################################
    ### NIGHTLY BUILD SCHEDULE                                                       ###
    ####################################################################################
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "schedule"'
      variables:
        DOCUMENTATION: "true"
      when: always
    ####################################################################################
    ### MERGE TO DEVELOP                                                             ###
    ####################################################################################
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"' # the only push to default branch is on merge
      variables:
        MERGE_TO_DEVELOP: "true"
        DOCUMENTATION: "true"
      when: always
    - when: never
