app_name: @project.artifactId@
app_version: @project.version@

spring:
  data:
    mongodb:
      auto-index-creation: true

feature:
  data:
    changestream:
      enabled: ${FEATURE_DATA_CHANGESTREAM_ENABLED:false}

uk:
  gov:
    dwp:
      health:
        changestream:
          channels:
            - collection: ${CHANGESTREAM_DOCUMENT_COLLECTION:document}
              routing-key: ${CHANGESTREAM_DOCUMENT_ROUTING_KEY:doc-sub-routing-key}
              database: ${CHANGESTREAM_DOCUMENT_ROUTER_DATABASE:document}
            - collection: ${CHANGESTREAM_SUBMISSION_COLLECTION:submission}
              routing-key: ${CHANGESTREAM_SUBMISSION_ROUTING_KEY:doc-sub-routing-key}
              database: ${CHANGESTREAM_SUBMISSION_ROUTER_DATABASE:submission}
            - collection: ${CHANGESTREAM_DRSUPLOAD_COLLECTION:drs_upload}
              routing-key: ${CHANGESTREAM_DRSUPLOAD_ROUTING_KEY:doc-sub-routing-key}
              database: ${CHANGESTREAM_DRSUPLOAD_ROUTER_DATABASE:drsupload}

---

spring:
  main:
    banner-mode: 'off'
  jmx:
    enabled: false
  config:
    activate:
      on-profile: dev
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: prometheus, info, health
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  health:
    mongo:
      enabled: false

feature:
  mongo:
    stable:
      api:
        enabled: ${FEATURE_MONGO_STABLE_API_ENABLED:true}