########################################################################################
###    Jobs specific to maven projects including:                                    ###
###      - code lint                                                                 ###
###      - unit test                                                                 ###
###      - code audit                                                                ###
########################################################################################


### TRIGGERS
.maven-build: &maven-build
  rules:
    - if: $BUILD_TYPE == "MAVEN"

.maven-not-merge: &maven-not-merge
  rules:
    - if: $BUILD_TYPE == "MAVEN" && $MERGE_TO_DEVELOP == null

### LINT
maven-lint:
  extends: .maven-lint-template
  <<: *maven-not-merge
  needs: []

maven-version-check:
  extends: .maven-version-check-template
  <<: *maven-not-merge
  needs: []

maven-plugin-check:
  extends: .maven-plugin-check-template
  <<: *maven-not-merge
  needs: []

### TEST
maven-verify:
  extends: .maven-verify-template
  <<: *maven-build
  allow_failure: false
  needs: []

maven-pitest:
  extends: .maven-pitest-template
  <<: *maven-build
  needs: []

### PACKAGE
maven-package:
  extends: .maven-package-template
  <<: *maven-build
  needs: [maven-verify]

### SCAN
maven-spotbugs:
  extends: .maven-spotbugs-template
  <<: *maven-build
  needs: [maven-verify]
