########################################################################################
###    Jobs to ensure pipeline compliance                                            ###
########################################################################################


### TRIGGERS
.build-not-merge: &build-not-merge
  rules:
    - if: $BUILD_TYPE && $MERGE == null

### COMPLIANCE
required-fragment-check:
  extends: .required-fragment-check-template
  variables:
    RULESET: MAVEN_CI
    FRAGMENT_INCLUDE_PATH: "$CI_PROJECT_DIR/gitlab-ci/config/fragments.yml"
  <<: *build-not-merge
  needs: []

fragment-version-check:
  extends: .fragment-version-check-template
  variables:
    FRAGMENT_INCLUDE_PATH: "$CI_PROJECT_DIR/gitlab-ci/config/fragments.yml"
  <<: *build-not-merge
  needs: []
