########################################################################################
###    Jobs to update the code version                                               ###
########################################################################################


### TRIGGERS
.version: &version
  rules:
    - if: $VERSION == "true"

### UPDATE VERSION
check-semver:
  extends: .check-semver-maven-template
  <<: *version
